### ISSUE TITLE
Add support for multiple images

### ISSUE THREAD

**Issue by wk-j** [i-bcircle/tesseract-service#2]
https://github.com/i-bcircle/tesseract-service/blob/26c060bff2e562a7b02717b720fd37f13f3b1b0a/app.py#L42

**Comment by panu00x** [comment]
![ภาพหน้าจอ 2562-08-22 เวลา 09 52 06](https://user-images.githubusercontent.com/42166587/63482371-dfdccd80-c4c2-11e9-8154-fc90b1fc73bc.png)
