### ISSUE TITLE
Preserve the position of output according to original image

### ISSUE THREAD

**Issue by wk-j** [i-bcircle/tesseract-service#4]
https://github.com/i-bcircle/tesseract-service/blob/d213f4acc13e9335c3932ec2846cccb6e1d030e6/app.py#L45-L47

Example

<img width="671" alt="text-position" src="https://user-images.githubusercontent.com/860704/63491261-f265ff80-c4e0-11e9-8965-b56fc5498ecb.png">

**Comment by panu00x** [comment]
![ภาพหน้าจอ 2562-08-22 เวลา 15 20 06](https://user-images.githubusercontent.com/42166587/63498907-031e7180-c4f1-11e9-8292-5465e522d177.png)
